config/routes.rb
RemoteVote::Application.routes.draw do
  devise_for :users 

  root :to => "assemblies#index"

  resources :categories, :only => [:index, :show ]

  resources :assemblies do
    resources :users
    resources :registration_numbers, :only => [:index, :new, :create]
    resources :tags
    resources :authorizations, :only => [:new,:create,:destroy]
    resources :proposals  do
      resources :amendments do
        resources :replies
      end
      resources :replies
    end
  end

  namespace :services do
    resources :assemblies do
      resources :proposals do
        resources :amendments do
          resources:replies
        end
        resources :replies
      end
    end
  end

end

app/views/shared/_actions.html.slim
nav.actions
  ul
    li = link_to t('global.reply'), "", :class => "reply"
    li = link_to t('global.flag'), "", :class => "flag"

app/views/shared/_navigation.html.slim
nav
  ul
    li = link_to t('global.navigation.home'), root_url
    li = link_to t('global.navigation.browse')
    - if user_signed_in?
      li = link_to t('global.navigation.preferences'), edit_user_registration_path
    li = link_to t('global.navigation.help')
    - if user_signed_in?
      li = link_to t('devise.sessions.sign_out'), destroy_user_session_path, :method => 'delete'
    - else
      li = link_to t('devise.sessions.sign_in'), new_user_session_path

app/views/shared/_tags.html.slim
- unless model.taxonomies.empty?  
  aside.tags
    - model.taxonomies.each do |taxonomy|
        = link_to "##{taxonomy.tag.name}", assembly_tag_url(@assembly.id, taxonomy.tag.name) 

app/views/shared/_vote.html.slim
aside.vote
  = link_to t('global.upvote'), "", :class => "up"
  h4 = model.net_votes
  = link_to t('global.downvote'), "", :class => "down"