config/routes.rb
RemoteVote::Application.routes.draw do
  devise_for :users 

  root :to => "assemblies#index"

  resources :categories, :only => [:index, :show ]

  resources :assemblies do
    resources :users
    resources :registration_numbers, :only => [:index, :new, :create]
    resources :tags
    resources :authorizations, :only => [:new,:create,:destroy]
    resources :proposals  do
      resources :amendments do
        resources :replies
      end
      resources :replies
    end
  end

  namespace :services do
    resources :assemblies do
      resources :proposals do
        resources :amendments do
          resources:replies
        end
        resources :replies
      end
    end
  end

end

app/models/proposal.rb
# Proposals are the heart of this application.
# Anyone can post a proposal, and proposals gain
# popularity by being voted for. A proposal can be
# ammended and replied to by any user. When proposals
# reach enough popularity, a facilitation user can push
# a proposal to being an official proposal of the GA.
# Once the proposal is pushed subsequent votes are binding.
class Proposal < ActiveRecord::Base
  belongs_to :assembly, :foreign_key => :uuid
  belongs_to :user
  has_many :binding_votes, :as => :bindable
  has_many :replies, :as => :replyable
  has_many :flags, :as => :flaggable
  has_many :amendments
  has_many :blocks

  validates :title, :length => {:minimum => 5}
  validates :body, :length => {:minimum => 140}

  include Voteable
  include Flaggable
  include Taggable

  class << self
    # Reorder by most popular proposals.
    #def most_popular(limit = false)
    #  if !limit
    #    joins(:votes).group('proposals.id').order('SUM(votes.upvote) DESC')
    #  else
    #    joins(:votes).group('proposals.id').order('SUM(votes.upvote) DESC').limit(limit)
    #  end
    #end

    # Find a proposals with binding votes
    def binding
      joins(:binding_votes)
    end
  end

  # See: app/models/block.rb
  def block(user_id)
    unless blocks.where(:user_id => user_id).exists?
      blocks.create(:user_id => user_id)
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  respond_to :html, :json

  def index
    @popular = Proposal.most_popular(10)
    @recent = Proposal.limit(10)

    respond_to do |format|
      format.html
      format.json { render :text => {:popular => @popular, :recent => @recent}.to_json }
    end
  end

  def show
    @proposal = @assembly.proposals.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :text => @proposal.to_json }
    end
  end

  def new
    @proposal = @assembly.proposals.build

    respond_to do |format|
      format.html
      format.json { render :text => @proposal.to_json }
    end
  end

  def create
    @proposal = @assembly.proposals.build(params[:proposal])

    if @proposal.save
      flash[:success] = t('proposals.create.success')
      
      respond_to do |format|
        format.html { redirect_to assembly_proposal_url(@assembly,@proposal) }
        format.json { render :text => @proposal.to_json }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render :text => @proposal.to_json }
      end
    end
  end

  def edit
    @proposal = @assembly.proposals.find(params[:id])
    authenticate_ownership(@proposal) and return

    respond_to do |format|
      format.html
      format.json { render :text => @proposal.to_json }
    end
  end

  def update
    @proposal = @assembly.proposals.find(params[:id])
    authenticate_ownership(@proposal)
    @proposal.title = params[:proposal][:title]
    @proposal.body = params[:proposal][:body]

    if @proposal.save!
      flash[:success] = t('proposals.update.success')
      
      respond_to do |format|
        format.html { redirect_to assembly_proposal_url(@assembly,@proposal) }
        format.json { render :text => @proposal.to_json }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render :text => @proposal.to_json }
      end
    end
  end

  def destroy
    @proposal = @assembly.proposals.find(params[:id])
    authenticate_ownership(@proposal)
    
    if @proposal.destroy
      respond_to do |format|
        format.html { redirect_to assembly_proposals_url(@assembly) }
        format.json { render :text => @proposal.to_json }
      end
    else
      flash[:error] = t('proposals.destroy.error')
      respond_to do |format|
        format.html { redirect_to assembly_proposal_url(@assembly,@proposal) }
        format.json { render :text => @proposal.to_json }
      end
    end
  end

end

app/controllers/services/proposals_controller.rb
class Services::ProposalsController < Services::ApplicationController

end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/services/proposals_helper.rb
module Services::ProposalsHelper
  
end

app/views/proposals/_form.html.slim
= form_for [assembly, proposal] do |f|
  .flash
    - if proposal.errors.any?
      = t('proposals.errors')
      - proposal.errors.full_messages.each do |error|
        .error = error
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  = f.submit t('proposals.submit'), :id => "submit"

app/views/proposals/_list.html.slim
- unless proposals.empty?
  ul.proposals.list
    - proposals.each do |proposal|
      li.proposals.item
        == render :partial => "proposals/single", :locals => { :proposal => proposal, :assembly => assembly }
- else
  p.proposals.none = t('proposals.none')

app/views/proposals/_single.html.slim
== render :partial => 'shared/vote', :locals => {:model => proposal}
article.proposal
  h3 = link_to proposal.title, assembly_proposal_path(assembly,proposal)
  .body = (params[:controller] == "proposals" && params[:action] == "show") ? clean_tags(proposal.body) : snippet(proposal.body, 500)
  == render :partial => 'shared/tags', :locals => {:model => proposal}
== render :partial => 'shared/actions', :locals => {:model => proposal}

app/views/proposals/edit.html.slim
= title t('proposals.update.title')
= render :partial => "form", :locals => {:proposal => @proposal, :assembly => @assembly}

app/views/proposals/index.html.slim
= title t('proposals.index.title', :assembly_title => @assembly.name)
== render :partial => "list", :locals => {:proposals => @popular, :assembly => @assembly}

app/views/proposals/new.html.slim
= title t('proposals.create.title')
== render :partial => "form", :locals => {:proposal => @proposal, :assembly => :assembly}

app/views/proposals/show.html.slim
= title(@proposal.title, false)
div.proposals.item
  == render :partial => 'proposals/single', :locals => {:assembly => @assembly, :proposal => @proposal}
div.amendments.column
  h3 = t('amendments.name.plural')
  == render :partial => 'amendments/list', :locals => { :amendments => @proposal.amendments, :assembly => @assembly }
div.replies.column
  h3 = t('replies.name.plural')
  == render :partial => 'replies/list', :locals => { :replies => @proposal.replies }