config/routes.rb
RemoteVote::Application.routes.draw do
  devise_for :users 

  root :to => "assemblies#index"

  resources :categories, :only => [:index, :show ]

  resources :assemblies do
    resources :users
    resources :registration_numbers, :only => [:index, :new, :create]
    resources :tags
    resources :authorizations, :only => [:new,:create,:destroy]
    resources :proposals  do
      resources :amendments do
        resources :replies
      end
      resources :replies
    end
  end

  namespace :services do
    resources :assemblies do
      resources :proposals do
        resources :amendments do
          resources:replies
        end
        resources :replies
      end
    end
  end

end

app/models/amendment.rb
# The Amendment class is just a post that belongs to a Proposal.
# A user will post an amendment when they feel a proposal could
# be improved. Amendments are voteable.
class Amendment < ActiveRecord::Base
  has_many :replies, :as => :replyable
  belongs_to :proposal
  belongs_to :user

  validates :title, :presence => true, :length => { :maximum => 140 }
  validates :body, :length => { :minimum => 140 }

  include Voteable
  include Flaggable
end

app/controllers/amendments_controller.rb
class AmendmentsController < ApplicationController

  respond_to :html, :json

  def index
    @amendments = Amendment.all

    respond_to do |format|
      format.html
      format.json { render :text => @amendments.to_json }
    end
  end

  def show
    @amendment = @proposal.amendments.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :text => @amendment.to_json }
    end
  end

  def new
    @amendment = @proposal.amendments.build

    respond_to do |format|
      format.html
      format.json { render :text => @amendment.to_json }
    end
  end

  def create
    @amendment = @proposal.amendments.build(params[:amendment])

    if @amendment.save
      flash[:success] = t('amendments.create.success')

      respond_to do |format|
        format.html { redirect_to assembly_proposal_amendment_url(@assembly,@proposal, @amendment) }
        format.json { render :text => @amendment.to_json }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render :text => @amendment.to_json }
      end
    end
  end

  def edit
    @amendment = Amendment.find(params[:id])
    authenticate_ownership(@amendment) and return

    respond_to do |format|
      format.html
      format.json { render :text => @amendment.to_json }
    end
  end

  def update
    @amendment = Amendment.find(params[:id])
    authenticate_ownership(@amendment) and return

    @amendment.title = params[:amendment][:title]
    @amendment.body = params[:amendment][:body]

    if @amendment.save
      flash[:success] = t('amendments.update.success')
      
      respond_to do |format|
        format.html { redirect_to assembly_proposal_amendment_url(@assembly,@proposal,@amendment) }
        format.json { render :text => @amendment.to_json }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render :text => @amendment.to_json }
      end
    end
  end

  def destroy
    @amendment = Amendment.find(params[:id])
    authenticate_ownership(@amendment) and return
    if @amendment.destroy
      flash[:notice] = t('amendments.destroy.success')
      
      respond_to do |format|
        format.html { redirect_to assembly_proposals_path(@assembly) }
        format.json { render :text => @amendment.to_json }
      end
    else
      flash[:error] = t('amendments.destroy.error')
      respond_to do |format|
        format.html { redirect_to assembly_proposal_path(@assembly,@propsal,@amendment) }
        format.json { render :text => @amendment.to_json }
      end
    end
  end

end

app/controllers/services/amendments_controller.rb
class Services::AmendmentsController < Services::ApplicationController
end

app/helpers/amendments_helper.rb
module AmendmentsHelper
end

app/helpers/services/amendments_helper.rb
module Services::AmendmentsHelper
end

app/views/amendments/_form.html.slim
= form_for [assembly, proposal, amendment] do |f|
  .flash
    - if amendment.errors.any?
      = t('amendments.errors')
      - amendment.errors.full_messages.each do |error|
        .error = error
  = f.text_field :title
  = f.text_area :body
  = f.submit t('amendments.submit'), :id => "submit"

app/views/amendments/_list.html.slim
- unless amendments.empty?
  ul.amendments.list
    - amendments.each do |amendment|
      li.amendments.item
        == render :partial => 'amendments/single', :locals => {:amendment => amendment}
- else
  p.amendments.none = t('amendments.none')

app/views/amendments/_single.html.slim
== render :partial => 'shared/vote', :locals => {:model => amendment}
article.amendment
  h3 = link_to amendment.title, assembly_proposal_amendment_path(amendment.proposal.assembly_uuid,amendment.proposal.id,amendment)
  .body = amendment.body
== render :partial => 'shared/actions', :locals => {:model => amendment}

app/views/amendments/edit.html.slim
= title t('amendments.update.title', :title => @amendment.title)
== render :partial => "form", :locals => { :assembly => @assembly, :proposal => @proposal, :amendment => @amendment }

app/views/amendments/index.html.slim
=title t('amendments.index.title', :proposal_title => @proposal.title)
== render :partial => "list", :locals => {:amendments => @amendments}

app/views/amendments/new.html.slim
= title t('amendments.create.title', :proposal_title => @proposal.title)
= form_for [@assembly,@proposal,@amendment] do |f|
  == render :partial => "form", :locals => {:assembly => @assembly, :proposal => @proposal, :amendment => @amendment }

app/views/amendments/show.html.slim
= title @amendment.title, false
== render :partial => 'amendments/single', :locals => {:amendment => @amendment}
== render :partial => 'replies/list', :locals => {:replies => @amendment.replies}